---
- name: restart-multipath
  service: name=multipath-tools state=restarted

- name: systemctl-reload
  command: systemctl daemon-reload

- name: update-grub
  command: update-grub

- name: restart-sshd
  service: name=sshd state=restarted

- name: sysctl-reload
  command: sysctl --system
  ignore_errors: yes
  when: container is not defined

- name: systemd-tmpfiles
  command: systemd-tmpfiles --create

