---
- name: Stop ubuntu multipathd being shit
  systemd:
    name: multipathd
    state: stopped
    enabled: no
    masked: yes
  tags:
    - systemd

- name: Remove unneeded services
  apt:
    name:
      - needrestart
      - snapd
      - cloud-init
    state: absent
    purge: yes
    autoremove: yes

- name: Install base packages that are not present on minimized systems
  apt:
    name:
      - vim
      - iputils-ping
      - open-vm-tools
      - jq
      - netplan.io
      - fdisk
      - software-properties-common
      - cpuid
      - rasdaemon
      - numactl
      - numad
      - numatop
      - sg3-utils-udev
    state: present

- name: Update /etc/hosts if needed
  template: src=hosts dest=/etc/hosts
  when: hostname is defined
  tags: hostname

- name: Fix default editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
  tags:
    - editor

- name: Turn off paste blocking
  lineinfile:
    path: /etc/bash.bashrc
    line: bind 'set enable-bracketed-paste off'
    create: yes

- name: Hard-code editor
  lineinfile:
    path: /etc/bash.bashrc
    line: export EDITOR=vim
    create: yes

- name: Hard-code visual
  lineinfile:
    path: /etc/bash.bashrc
    line: export VISUAL=vim
    create: yes

- name: Stop rsyslog from dropping privs
  lineinfile:
    path: /etc/rsyslog.conf
    regex: '^.PrivDropTo'
    state: absent
  tags: rsyslog

- name: Update grub with eth network names and init_on_alloc=0
  copy:
    src: grubdefault
    dest: /etc/default/grub
  notify: update-grub
  register: grub
  tags:
    - net

- name: Put our /etc/sysctl.d files in place
  copy:
    src: "{{ item }}"
    dest: /etc/sysctl.d/
  with_items:
    - 10-keepalives.conf
    - 50-zfs-server.conf
    - 60-faster-tcp.conf
  notify: sysctl-reload
  tags:
    - sysctl

- meta: flush_handlers
  tags:
    - net
    - sysctl

- name: Make sure rasdaemon is ready to catch any hardware errors
  service:
    name: rasdaemon
    state: started
    enabled: true

- name: Create default ssh config
  copy:
    src: sshconfig
    dest: /root/.ssh/config
    force: no
  tags:
    - ssh

- name: Set system start timeout to 60s
  lineinfile:
    path: /etc/systemd/system.conf
    regex: '^#?DefaultTimeoutStartSec='
    line: DefaultTimeoutStartSec=60s
  tags:
    - systemd

- name: Set system stop timeout to 30s
  lineinfile:
    path: /etc/systemd/system.conf
    regex: '^#?DefaultTimeoutStopSec='
    line: DefaultTimeoutStopSec=30s
  tags:
    - systemd

- name: Never hang waiting for network connections
  systemd:
    name: systemd-networkd-wait-online.service
    state: stopped
    enabled: no
    masked: yes
  tags:
    - systemd

- name: Make sure memory deduplication is disabled
  copy:
    src: ksm.conf
    dest: /etc/tmpfiles.d/
  tags:
    - systemd
    - ksm
  notify:
    - systemd-tmpfiles

- name: Is resolv.conf a symlink?
  stat:
    path: /etc/resolv.conf
  register: rconf
  tags:
    - dns

- name: Delete symlink
  file:
    state: absent
    path: /etc/resolv.conf
  when: forcedns is defined and rconf.stat.islnk
  tags:
    - dns

- name: Create valid /etc/resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
  when: forcedns is defined and rconf.stat.islnk
  tags:
    - dns

# U22.04 has SSH8, which disables rsa keys.
- name: Allow ssh-rsa in ssh keys
  lineinfile:
    path: /etc/ssh/ssh_config
    state: present
    insertafter: ^Host
    regexp: 'PubkeyAcceptedKeyTypes '
    line: "    PubkeyAcceptedKeyTypes +ssh-rsa"

- name: Enable agent forwarding
  lineinfile:
    path: /etc/ssh/ssh_config
    state: present
    insertafter: ^Host
    regexp: 'ForwardAgent '
    line: "    ForwardAgent yes"

- meta: flush_handlers
